spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://88770143-3fe2-454b-85be-31afbacbef33.private.rds.cloud.toast.com:13306/rds_mssql_alpha?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: rds
      password: rds!#%135
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      connection-timeout: 1000
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          batch_size: 500
        query:
          in_clause_parameter_padding: true

server:
  port: 10081